# Header
navname: WzZH's Blog

# navigatior items
nav:
  文章: /archives
  分类: /category
  标签: /tag
  关于: /about

# favicon
favicon: https://jihulab.com/Hide927/blogimages/-/raw/main/pictures/202210292140887.png

# Profile
nickname: WzZH

### this variable is MarkDown form.
description: Accept who you are but never settle for what you can be.
avatar: https://jihulab.com/Hide927/blogimages/-/raw/main/pictures/202210292140887.png

# main menu navigation
## links key words should not be changed.
## Complete url after key words.
## Unused key can be commented out.
links:
  Blog: /archives
  Youxiang: mailto:wangzihang927@foxmail.com
  # Category:
  # Tags: 
  # Link:
  # Resume:
  # Publish:
  # Trophy:
  # Gallery:
  # RSS:
  # AliPay:
  # LinkedIn:
  # FaceBook:
  Github: https://github.com/Hide927
  Twitter: https://twitter.com/Wonderful927
  # Skype:
  # CodeSandBox:
  # CodePen:
  # Sketch:
  # Gitlab:
  # Dribbble:
  # Instagram:
  # Reddit:
  # YouTube:
  # QQ:
  ZhiHu: https://www.zhihu.com/people/wei-xiao-ci-ke-89
  Weibo: https://weibo.com/u/6361743068
  # WeChat:

# how links show: you have 2 choice--text or icon.
links_text_enable: false
links_icon_enable: true

# Post page
## Post_meta
post_meta_enable: true

post_author_enable: false
post_date_enable: true
post_updated_enable: true
post_category_enable: true
post_view_counter_enable: true
## Post copyright
post_copyright_enable: true

post_copyright_author_enable: true
post_copyright_permalink_enable: true
post_copyright_license_enable: true
post_copyright_license_text: 本博客所有文章除特别声明外，均采用 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC-BY-NC-SA-4.0</a> 许可协议。转载请注明出处。
post_copyright_slogan_enable: false
post_copyright_slogan_text: Why so serious?
## toc
post_toc_enable: true

# Page
page_title_enable: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# stylesheets loaded in the <head>
stylesheets:
  - /css/style.css

# scripts loaded in the end of the body
scripts:
  - /js/script.js
  - /js/tocbot.min.js
    # tscanlin/tocbot: Build a table of contents from headings in an HTML document.
    # https://github.com/tscanlin/tocbot
  - https://cdn.bootcss.com/jquery/3.1.1/jquery.min.js
  - /js/codecopy.js
  - https://cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js

# plugin functions
## Mathjax: Math Formula Support
## https://www.mathjax.org
mathjax:
  enable: true
  import: demand # global or demand
  ## global: all pages will load mathjax,this will degrade performance and some grammers may be parsed wrong.
  ## demand: Recommend option,if your post need fomula, you can declare 'mathjax: true' in Front-matter

# since year
since_year: 2021

# waline comments
waline:
  enable: true

# site view counter
visit_counter: 
  site_uv: true
  site_pv: true